---
- name: Delete and eradictae snapshot of database volumes with suffix {{ suffix }}
  purefa_snap:
    name: "{{ source }}"
    suffix: "{{ suffix }}" 
    eradicate: true
    fa_url: "{{ RedDotX.ip }}"
    api_token: "{{ RedDotX.api_token }}"
    state: absent
 