---
# Check to see if ASM DG's are not mounted?
- name: check to see if ASM disk groups are mounted 
  shell: sudo -iu {{ tgt_gu}} asmcmd lsdg | egrep " {{ targetVol.vol1.dgname }}| {{ targetVol.vol2.dgname }}"
  register: asmcheck
  failed_when: asmcheck.rc ==0 or asmcheck.rc >=2
  ignore_errors: True

# Mount ASM disk groups
- name: Mount ASM disk groups 
  shell: '{{ tgt_dir }}/mountASMdg.sh > mountASMdg.log 2>&1'
  args:
    chdir: "{{ tgt_dir }}" 
  when: asmcheck.stdout == ""
