---
- name: "Overwrite existing pure volume {{ item.value.target }} with snapshot {{ item.value.source }}.{{ suffix }}"
  purefa_snap:
    name: "{{ item.value.source }}"
    suffix: "{{ suffix }}"
    target: "{{ item.value.target }}"
    overwrite: true
    fa_url: "{{ RedDotX.ip }}"
    api_token: "{{ RedDotX.api_token }}"
    state: copy
  with_dict: "{{ volmap }}"
  