---
# Check to see if Database is up?
- name: check to see if database is up 
  shell: ps -ef | grep -w [o]ra_smon_{{ tgt_db }}
  register: dbcheck
  failed_when: dbcheck.rc ==0 or dbcheck.rc >=2
  ignore_errors: True

# Startup target database
- name: startup database
  shell: '{{ tgt_dir }}/startupDB.sh > startupDB.log'
  args:
    chdir: "{{ tgt_dir }}"
  when: dbcheck.stdout == ""
  register: startup
