---
- name: Create snapshot of database volumes with suffix {{ suffix }}
  purefa_snap:
    name: "{{ source }}"
    suffix: "{{ suffix }}" 
    fa_url: "{{ array.ip }}"
    api_token: "{{ array.array_token }}"
    state: present
 